In [1]:
# Youssef Alaa

In [2]:
import selenium
from selenium import webdriver

In [3]:
driver = webdriver.Chrome()

In [4]:
driver.get(r'https://www.imdb.com/chart/top/')

In [5]:
Movie_Name = driver.find_elements("xpath","//div[@class='flex items-center gap-xs']/ul[@class='ipc-inline-list ipc-inline-list--show-dividers base']/div[@class='ipc-title ipc-title--base ipc-title--title ipc-title-link-no-icon ipc-title--on-textPrimary sc-7d5a9511-2 lexyFm cli-title with-margin']/a[@class='ipc-title-link-wrapper']/h4[@class='ipc-title__text']")

In [6]:
Movie_Name

[<selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.38")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.39")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.40")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.41")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.42")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.43")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.44")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.45")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.46")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.47")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.48")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.49")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.50")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.51")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.52")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.53")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.54")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.55")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.56")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.57")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.58")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.59")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.60")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.61")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.62")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.63")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.64")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.65")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.66")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.67")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.68")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.69")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.70")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.71")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.72")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.73")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.74")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.75")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.76")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.77")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.78")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.79")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.80")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.81")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.82")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.83")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.84")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.85")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.86")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.87")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.88")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.89")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.90")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.91")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.92")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.93")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.94")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.95")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.96")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.97")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.98")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.99")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.100")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.101")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.102")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.103")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.104")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.105")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.106")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.107")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.108")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.109")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.110")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.111")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.112")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.113")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.114")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.115")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.116")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.117")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.118")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.119")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.120")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.121")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.122")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.123")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.124")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.125")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.126")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.127")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.128")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.129")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.130")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.131")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.132")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.133")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.134")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.135")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.136")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.137")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.138")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.139")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.140")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.141")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.142")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.143")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.144")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.145")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.146")>,

In [7]:
for i in Movie_Name:
    print(i.text)

The Shawshank Redemption
The Godfather
The Dark Knight
The Godfather Part II
The Lord of the Rings: The Return of the King
12 Angry Men
Schindler's List
The Lord of the Rings: The Fellowship of the Ring
Pulp Fiction
The Lord of the Rings: The Two Towers
The Good, the Bad and the Ugly
Forrest Gump
Fight Club
Inception
Star Wars: Episode V - The Empire Strikes Back
The Matrix
Interstellar
GoodFellas
One Flew Over the Cuckoo's Nest
Seven
It's a Wonderful Life
The Silence of the Lambs
Saving Private Ryan
Seven Samurai
The Green Mile
City of God
Life Is Beautiful
Terminator 2: Judgment Day
Back to the Future
Star Wars: Episode IV - A New Hope
Kill Bill: The Whole Bloody Affair
Spirited Away
Gladiator
The Pianist
Parasite
Grave of the Fireflies
Harakiri
Psycho
The Lion King
The Departed
Whiplash
The Prestige
American History X
Spider-Man: Across the Spider-Verse
Léon: The Professional
Cinema Paradiso
Casablanca
The Intouchables
The Usual Suspects
Django Unchained
Alien
Rear Window
Modern Times
Once Upon a Time in the West
City Lights
WALL·E
Apocalypse Now
The Odyssey
Memento
Avengers: Infinity War
Dune: Part Two
Raiders of the Lost Ark
Spider-Man: Into the Spider-Verse
The Lives of Others
Sunset Boulevard
Witness for the Prosecution
Paths of Glory
The Shining
Inglourious Basterds
The Great Dictator
Aliens
12th Fail
High and Low
Avengers: Endgame
Good Will Hunting
Coco
The Dark Knight Rises
Toy Story
Amadeus
Your Name.
Das Boot
Braveheart
3 Idiots
Princess Mononoke
Oldboy
Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb
American Beauty
Capernaum
Singin' in the Rain
Once Upon a Time in America
Joker
Toy Story 3
Star Wars: Episode VI - Return of the Jedi
Come and See
Requiem for a Dream
Ikiru
Incendies
The Hunt
Eternal Sunshine of the Spotless Mind
The Apartment
Lawrence of Arabia
Attack on Titan: The Last Attack
Heat
Scarface
Reservoir Dogs
2001: A Space Odyssey
Up
Double Indemnity
Like Stars on Earth
North by Northwest
Full Metal Jacket
I Swear
A Separation
M
Die Hard
Amélie
Vertigo
Citizen Kane
To Kill a Mockingbird
Indiana Jones and the Last Crusade
The Sting
A Clockwork Orange
Metropolis
1917
Snatch
The Wolf of Wall Street
Woman in the Dunes
The Truman Show
Downfall
Shutter Island
L.A. Confidential
Dangal
Green Book
Bicycle Thieves
Judgment at Nuremberg
Jurassic Park
Oppenheimer
Batman Begins
For a Few Dollars More
Hamilton
There Will Be Blood
Some Like It Hot
Taxi Driver
The Father
The Kid
The Sixth Sense
All About Eve
Ran
Casino
The Thing
No Country for Old Men
Prisoners
Top Gun: Maverick
Kill Bill: Vol. 1
Project Hail Mary
Unforgiven
Pan's Labyrinth
A Beautiful Mind
Howl's Moving Castle
The Treasure of the Sierra Madre
Finding Nemo
Demon Slayer: Kimetsu No Yaiba Infinity Castle
Klaus
Yojimbo
The Elephant Man
The Great Escape
Monty Python and the Holy Grail
Dial M for Murder
The Secret in Their Eyes
Gone with the Wind
Lock, Stock and Two Smoking Barrels
Chinatown
Catch Me If You Can
V for Vendetta
The Best of Youth
Inside Out
Dead Poets Society
Trainspotting
Three Billboards Outside Ebbing, Missouri
Harry Potter and the Deathly Hallows: Part 2
The Bridge on the River Kwai
Rashomon
Barry Lyndon
The Wild Robot
Ben-Hur
Warrior
Hacksaw Ridge
Fargo
Mad Max: Fury Road
Million Dollar Baby
Ratatouille
Children of Heaven
My Neighbor Totoro
Gran Torino
Raging Bull
12 Years a Slave
How to Train Your Dragon
Memories of Murder
The Grand Budapest Hotel
Before Sunrise
Blade Runner
Monsters, Inc.
Gone Girl
Ford v Ferrari
Jaws
In the Name of the Father
Spider-Man: No Way Home
Wild Tales
The Gold Rush
Chainsaw Man - The Movie: Reze Arc
Sherlock Jr.
Mary and Max
A Silent Voice: The Movie
The Wages of Fear
The Deer Hunter
Logan
Rocky
Pirates of the Caribbean: The Curse of the Black Pearl
The General
Mr. Smith Goes to Washington
Tokyo Story
La haine
Spotlight
The Sound of Music
Maharaja
Jai Bhim
The Terminator
Wild Strawberries
On the Waterfront
The Best Years of Our Lives
The Third Man
The Chaos Class Failed the Class
The Big Lebowski
The Incredibles
Before Sunset
Hachi: A Dog's Tale
Room
Hotel Rwanda
The Exorcist
The Seventh Seal
Platoon
The Iron Giant
Rush
Stand by Me
The Wizard of Oz
The Battle of Algiers
My Father and My Son
The Passion of Joan of Arc
The Handmaiden
Hera Pheri

In [8]:
len(Movie_Name)

250

In [9]:
Movie_Name[-1].text

'Hera Pheri'

In [10]:
Movie_Name[-2].text

'The Handmaiden'

In [11]:
Movie_Name[-3].text

'The Passion of Joan of Arc'

In [12]:
Movie_Name[-4].text

'My Father and My Son'

In [13]:
Release_Year = driver.find_elements("xpath","//div[@class='sc-777cc4aa-5 bGabDQ cli-title-metadata']/ul[@class='ipc-inline-list ipc-inline-list--show-dividers ipc-inline-list--no-wrap ipc-inline-list--inline base']/li[1]")

In [14]:
Release_Year

[<selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.299")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.300")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.301")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.302")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.303")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.304")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.305")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.306")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.307")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.308")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.309")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.310")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.311")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.312")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.313")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.314")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.315")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.316")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.317")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.318")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.319")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.320")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.321")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.322")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.323")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.324")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.325")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.326")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.327")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.328")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.329")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.330")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.331")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.332")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.333")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.334")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.335")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.336")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.337")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.338")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.339")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.340")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.341")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.342")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.343")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.344")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.345")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.346")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.347")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.348")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.349")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.350")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.351")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.352")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.353")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.354")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.355")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.356")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.357")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.358")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.359")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.360")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.361")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.362")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.363")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.364")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.365")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.366")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.367")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.368")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.369")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.370")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.371")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.372")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.373")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.374")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.375")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.376")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.377")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.378")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.379")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.380")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.381")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.382")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.383")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.384")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.385")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.386")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.387")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.388")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.389")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.390")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.391")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.392")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.393")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.394")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.395")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.396")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.397")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.398")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.399")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.400")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.401")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.402")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.403")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.404")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.405")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.406")>,

In [15]:
for i in Release_Year:
    print(i.text)

1994
1972
2008
1974
2003
1957
1993
2001
1994
2002
1966
1994
1999
2010
1980
1999
2014
1990
1975
1995
1946
1991
1998
1954
1999
2002
1997
1991
1985
1977
2004
2001
2000
2002
2019
1988
1962
1960
1994
2006
2014
2006
1998
2023
1994
1988
1942
2011
1995
2012
1979
1954
1936
1968
1931
2008
1979
2026
2000
2018
2024
1981
2018
2006
1950
1957
1957
1980
2009
1940
1986
2023
1963
2019
1997
2017
2012
1995
1984
2016
1981
1995
2009
1997
2003
1964
1999
2018
1952
1984
2019
2010
1983
1985
2000
1952
2010
2012
2004
1960
1962
2024
1995
1983
1992
1968
2009
1944
2007
1959
1987
2025
2011
1931
1988
2001
1958
1941
1962
1989
1973
1971
1927
2019
2000
2013
1964
1998
2004
2010
1997
2016
2018
1948
1961
1993
2023
2005
1965
2020
2007
1959
1976
2020
1921
1999
1950
1985
1995
1982
2007
2013
2022
2003
2026
1992
2006
2001
2004
1948
2003
2025
2019
1961
1980
1963
1975
1954
2009
1939
1998
1974
2002
2005
2003
2015
1989
1996
2017
2011
1957
1950
1975
2024
1959
2011
2016
1996
2015
2004
2007
1997
1988
2008
1980
2013
2010
2003
2014
1995
1982
2001
2014
2019
1975
1993
2021
2014
1925
2025
1924
2009
2016
1953
1978
2017
1976
2003
1926
1939
1953
1995
2015
1965
2024
2021
1984
1957
1954
1946
1949
1975
1998
2004
2004
2009
2015
2004
1973
1957
1986
1999
2013
1986
1939
1966
2005
1928
2016
2000

In [16]:
len(Release_Year)

250

In [17]:
Runtime = driver.find_elements("xpath","//div[@class='sc-777cc4aa-5 bGabDQ cli-title-metadata']/ul[@class='ipc-inline-list ipc-inline-list--show-dividers ipc-inline-list--no-wrap ipc-inline-list--inline base']/li[2]")

In [18]:
Runtime

[<selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.557")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.558")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.559")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.560")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.561")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.562")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.563")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.564")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.565")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.566")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.567")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.568")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.569")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.570")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.571")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.572")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.573")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.574")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.575")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.576")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.577")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.578")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.579")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.580")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.581")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.582")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.583")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.584")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.585")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.586")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.587")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.588")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.589")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.590")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.591")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.592")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.593")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.594")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.595")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.596")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.597")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.598")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.599")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.600")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.601")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.602")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.603")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.604")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.605")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.606")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.607")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.608")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.609")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.610")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.611")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.612")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.613")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.614")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.615")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.616")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.617")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.618")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.619")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.620")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.621")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.622")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.623")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.624")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.625")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.626")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.627")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.628")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.629")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.630")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.631")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.632")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.633")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.634")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.635")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.636")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.637")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.638")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.639")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.640")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.641")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.642")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.643")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.644")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.645")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.646")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.647")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.648")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.649")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.650")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.651")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.652")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.653")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.654")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.655")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.656")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.657")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.658")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.659")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.660")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.661")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.662")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.663")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9110962c0aa0a33feb477763f4fbf4f4", element="f.7ED0AB0F327C37E6FBF451D77C14CEF7.d.B236E5BD66D3FE1551F60A2CDFE3CFE1.e.664")>,

In [19]:
for i in Runtime:
    print(i.text)

2h 22m
2h 55m
2h 32m
3h 22m
3h 21m
1h 36m
3h 16m
2h 58m
2h 34m
2h 59m
2h 58m
2h 22m
2h 19m
2h 28m
2h 4m
2h 16m
2h 49m
2h 25m
2h 13m
2h 7m
2h 10m
1h 58m
2h 49m
3h 27m
3h 9m
2h 10m
1h 56m
2h 17m
1h 56m
2h 1m
4h 13m
2h 4m
2h 35m
2h 30m
2h 12m
1h 28m
2h 13m
1h 49m
1h 28m
2h 31m
1h 46m
2h 10m
1h 59m
2h 20m
1h 50m
2h 54m
1h 42m
1h 52m
1h 46m
2h 45m
1h 57m
1h 52m
1h 27m
2h 25m
1h 27m
1h 38m
2h 27m
2h 52m
1h 53m
2h 29m
2h 46m
1h 55m
1h 57m
2h 17m
1h 50m
1h 56m
1h 28m
2h 26m
2h 33m
2h 5m
2h 17m
2h 27m
2h 23m
3h 1m
2h 6m
1h 45m
2h 44m
1h 21m
2h 40m
1h 46m
2h 29m
2h 58m
2h 50m
2h 13m
2h
1h 35m
2h 2m
2h 6m
1h 43m
3h 49m
2h 2m
1h 43m
2h 11m
2h 22m
1h 42m
2h 23m
2h 11m
1h 55m
1h 48m
2h 5m
3h 47m
2h 25m
2h 50m
2h 50m
1h 39m
2h 29m
1h 36m
1h 47m
2h 42m
2h 16m
1h 56m
2h
2h 3m
1h 39m
2h 12m
2h 2m
2h 8m
1h 59m
2h 9m
2h 7m
2h 9m
2h 16m
2h 30m
1h 59m
1h 42m
3h
2h 27m
1h 43m
2h 36m
2h 18m
2h 18m
2h 41m
2h 10m
1h 29m
2h 59m
2h 7m
3h
2h 20m
2h 12m
2h 40m
2h 38m
2h 1m
1h 54m
1h 37m
1h 8m
1h 47m
2h 18m
2h 40m
2h 58m
1h 49m
2h 2m
2h 33m
2h 10m
1h 51m
2h 36m
2h 10m
1h 58m
2h 15m
1h 59m
2h 6m
1h 40m
2h 35m
1h 36m
1h 50m
2h 4m
2h 52m
1h 31m
1h 45m
2h 9m
3h 58m
1h 47m
2h 10m
2h 21m
2h 12m
6h 14m
1h 35m
2h 8m
1h 33m
1h 55m
2h 10m
2h 41m
1h 28m
3h 5m
1h 42m
3h 32m
2h 20m
2h 19m
1h 38m
2h
2h 12m
1h 51m
1h 29m
1h 26m
1h 56m
2h 9m
2h 14m
1h 38m
2h 11m
1h 39m
1h 41m
1h 57m
1h 32m
2h 29m
2h 32m
2h 4m
2h 13m
2h 28m
2h 2m
1h 35m
1h 40m
45m
1h 32m
2h 10m
2h 36m
3h 3m
2h 17m
2h
2h 23m
1h 18m
2h 9m
2h 17m
1h 38m
2h 9m
2h 54m
2h 21m
2h 44m
1h 47m
1h 32m
1h 48m
2h 50m
1h 44m
1h 35m
1h 57m
1h 55m
1h 20m
1h 33m
1h 58m
2h 1m
2h 2m
1h 36m
2h
1h 26m
2h 3m
1h 29m
1h 42m
2h 1m
1h 52m
1h 54m
2h 25m
2h 36m

In [20]:
len(Runtime)

250

In [21]:
Certificate = driver.find_elements("xpath","//div[@class='sc-777cc4aa-5 bGabDQ cli-title-metadata']/ul[@class='ipc-inline-list ipc-inline-list--show-dividers ipc-inline-list--no-wrap ipc-inline-list--inline base']/li[3]")

In [22]:
for i in Certificate:
    print(i.text)

R
R
PG-13
R
PG-13
Approved
R
PG-13
R
PG-13
R
PG-13
R
PG-13
PG
R
PG-13
R
R
R
PG
R
R
Not Rated
R
R
PG-13
R
PG
PG
Unrated
PG
R
R
R
Not Rated
Not Rated
R
G
R
R
PG-13
R
PG
R
PG
PG
R
R
R
R
PG
G
PG-13
G
G
R
R
R
PG-13
PG-13
PG
PG
R
Approved
Approved
Approved
R
R
G
R
Not Rated
PG-13
R
PG
PG-13
G
PG
R
PG-13
PG-13
R
PG
R
R
G
R
R
G
PG
Not Rated
NC-17
Not Rated
R
R
R
Approved
Approved
R
R
R
G
PG
Approved
PG
Approved
R
R
PG-13
Passed
R
R
PG
PG
Approved
PG-13
PG
R
Passed
R
R
R
Not Rated
PG
R
R
R
Not Rated
PG-13
Not Rated
Approved
PG-13
R
PG-13
R
PG-13
R
Approved
R
PG-13
Passed
PG-13
Approved
R
R
R
R
R
PG-13
R
PG-13
R
R
PG-13
PG
Approved
G
R
PG
Not Rated
PG
Approved
PG
PG
R
G
R
R
PG-13
R
R
PG
PG
R
R
PG-13
PG
Not Rated
PG
PG
G
PG-13
R
R
R
PG-13
G
PG
G
R
R
R
PG
Not Rated
R
R
R
G
R
PG-13
PG
R
PG-13
R
Approved
R
Passed
Not Rated
Not Rated
Not Rated
R
R
PG
PG-13
Passed
Approved
Not Rated
Not Rated
R
G
TV-MA
R
Not Rated
Approved
Approved
Approved
R
PG
R
G
R
PG-13
R
Not Rated
R
PG
R
R
G
Not Rated
Not Rated
Passed
Not Rated
Not Rated

In [23]:
len(Certificate)

244

In [24]:
Rate = driver.find_elements("xpath","//div[@class='sc-ce3de6cc-0 icOjAa sc-777cc4aa-2 fyJMVp cli-ratings-container']/span[@class='ipc-rating-star ipc-rating-star--base ipc-rating-star--imdb ratingGroup--imdb-rating']/span[@class='ipc-rating-star--rating']")

In [25]:
for i in Rate:
    print(i.text)

9.3
9.2
9.1
9.0
9.0
9.0
9.0
8.9
8.8
8.8
8.8
8.8
8.8
8.8
8.7
8.7
8.7
8.7
8.6
8.6
8.6
8.6
8.6
8.6
8.6
8.6
8.6
8.6
8.5
8.6
8.7
8.6
8.5
8.5
8.5
8.5
8.6
8.5
8.5
8.5
8.5
8.5
8.5
8.5
8.5
8.5
8.5
8.5
8.5
8.5
8.4
8.4
8.5
8.5
8.5
8.4
8.4
8.5
8.4
8.4
8.4
8.4
8.4
8.4
8.4
8.4
8.4
8.4
8.4
8.4
8.4
8.7
8.4
8.4
8.4
8.4
8.4
8.3
8.4
8.4
8.3
8.3
8.4
8.3
8.3
8.3
8.3
8.4
8.3
8.3
8.3
8.3
8.3
8.3
8.3
8.3
8.3
8.3
8.3
8.3
8.3
8.9
8.3
8.3
8.2
8.3
8.3
8.3
8.3
8.3
8.2
8.4
8.3
8.3
8.2
8.2
8.2
8.2
8.2
8.2
8.2
8.2
8.2
8.2
8.2
8.2
8.4
8.2
8.2
8.2
8.2
8.3
8.2
8.2
8.3
8.2
8.2
8.2
8.2
8.3
8.2
8.2
8.2
8.2
8.2
8.2
8.2
8.2
8.2
8.2
8.2
8.2
8.2
8.2
8.2
8.2
8.2
8.2
8.2
8.2
8.2
8.4
8.2
8.2
8.2
8.2
8.1
8.1
8.2
8.2
8.1
8.1
8.1
8.1
8.4
8.1
8.1
8.1
8.1
8.1
8.1
8.1
8.1
8.1
8.1
8.1
8.1
8.1
8.1
8.1
8.1
8.2
8.1
8.1
8.1
8.1
8.1
8.1
8.1
8.1
8.1
8.1
8.1
8.1
8.1
8.1
8.1
8.1
8.1
8.3
8.1
8.1
8.2
8.1
8.1
8.1
8.1
8.1
8.1
8.1
8.1
8.1
8.1
8.1
8.3
8.6
8.1
8.1
8.1
8.1
8.1
8.4
8.1
8.0
8.1
8.1
8.1
8.1
8.1
8.1
8.0
8.1
8.1
8.1
8.1
8.1
8.2
8.1
8.1
8.2

In [26]:
len(Rate)

250

In [27]:
Rate[-1].text

'8.2'

In [28]:
Rate[-2].text

'8.1'

In [29]:
# Nadeen

In [30]:
print("Movie Names:", len(Movie_Name))
print("Release Years:", len(Release_Year))
print("Runtime:", len(Runtime))
print("Certificates:", len(Certificate))
print("Ratings:", len(Rate))

Movie Names: 250
Release Years: 250
Runtime: 250
Certificates: 244
Ratings: 250

In [31]:
for i in range(len(Movie_Name)):
    print(i, Movie_Name[i].text)

0 The Shawshank Redemption
1 The Godfather
2 The Dark Knight
3 The Godfather Part II
4 The Lord of the Rings: The Return of the King
5 12 Angry Men
6 Schindler's List
7 The Lord of the Rings: The Fellowship of the Ring
8 Pulp Fiction
9 The Lord of the Rings: The Two Towers
10 The Good, the Bad and the Ugly
11 Forrest Gump
12 Fight Club
13 Inception
14 Star Wars: Episode V - The Empire Strikes Back
15 The Matrix
16 Interstellar
17 GoodFellas
18 One Flew Over the Cuckoo's Nest
19 Seven
20 It's a Wonderful Life
21 The Silence of the Lambs
22 Saving Private Ryan
23 Seven Samurai
24 The Green Mile
25 City of God
26 Life Is Beautiful
27 Terminator 2: Judgment Day
28 Back to the Future
29 Star Wars: Episode IV - A New Hope
30 Kill Bill: The Whole Bloody Affair
31 Spirited Away
32 Gladiator
33 The Pianist
34 Parasite
35 Grave of the Fireflies
36 Harakiri
37 Psycho
38 The Lion King
39 The Departed
40 Whiplash
41 The Prestige
42 American History X
43 Spider-Man: Across the Spider-Verse
44 Léon: The Professional
45 Cinema Paradiso
46 Casablanca
47 The Intouchables
48 The Usual Suspects
49 Django Unchained
50 Alien
51 Rear Window
52 Modern Times
53 Once Upon a Time in the West
54 City Lights
55 WALL·E
56 Apocalypse Now
57 The Odyssey
58 Memento
59 Avengers: Infinity War
60 Dune: Part Two
61 Raiders of the Lost Ark
62 Spider-Man: Into the Spider-Verse
63 The Lives of Others
64 Sunset Boulevard
65 Witness for the Prosecution
66 Paths of Glory
67 The Shining
68 Inglourious Basterds
69 The Great Dictator
70 Aliens
71 12th Fail
72 High and Low
73 Avengers: Endgame
74 Good Will Hunting
75 Coco
76 The Dark Knight Rises
77 Toy Story
78 Amadeus
79 Your Name.
80 Das Boot
81 Braveheart
82 3 Idiots
83 Princess Mononoke
84 Oldboy
85 Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb
86 American Beauty
87 Capernaum
88 Singin' in the Rain
89 Once Upon a Time in America
90 Joker
91 Toy Story 3
92 Star Wars: Episode VI - Return of the Jedi
93 Come and See
94 Requiem for a Dream
95 Ikiru
96 Incendies
97 The Hunt
98 Eternal Sunshine of the Spotless Mind
99 The Apartment
100 Lawrence of Arabia
101 Attack on Titan: The Last Attack
102 Heat
103 Scarface
104 Reservoir Dogs
105 2001: A Space Odyssey
106 Up
107 Double Indemnity
108 Like Stars on Earth
109 North by Northwest
110 Full Metal Jacket
111 I Swear
112 A Separation
113 M
114 Die Hard
115 Amélie
116 Vertigo
117 Citizen Kane
118 To Kill a Mockingbird
119 Indiana Jones and the Last Crusade
120 The Sting
121 A Clockwork Orange
122 Metropolis
123 1917
124 Snatch
125 The Wolf of Wall Street
126 Woman in the Dunes
127 The Truman Show
128 Downfall
129 Shutter Island
130 L.A. Confidential
131 Dangal
132 Green Book
133 Bicycle Thieves
134 Judgment at Nuremberg
135 Jurassic Park
136 Oppenheimer
137 Batman Begins
138 For a Few Dollars More
139 Hamilton
140 There Will Be Blood
141 Some Like It Hot
142 Taxi Driver
143 The Father
144 The Kid
145 The Sixth Sense
146 All About Eve
147 Ran
148 Casino
149 The Thing
150 No Country for Old Men
151 Prisoners
152 Top Gun: Maverick
153 Kill Bill: Vol. 1
154 Project Hail Mary
155 Unforgiven
156 Pan's Labyrinth
157 A Beautiful Mind
158 Howl's Moving Castle
159 The Treasure of the Sierra Madre
160 Finding Nemo
161 Demon Slayer: Kimetsu No Yaiba Infinity Castle
162 Klaus
163 Yojimbo
164 The Elephant Man
165 The Great Escape
166 Monty Python and the Holy Grail
167 Dial M for Murder
168 The Secret in Their Eyes
169 Gone with the Wind
170 Lock, Stock and Two Smoking Barrels
171 Chinatown
172 Catch Me If You Can
173 V for Vendetta
174 The Best of Youth
175 Inside Out
176 Dead Poets Society
177 Trainspotting
178 Three Billboards Outside Ebbing, Missouri
179 Harry Potter and the Deathly Hallows: Part 2
180 The Bridge on the River Kwai
181 Rashomon
182 Barry Lyndon
183 The Wild Robot
184 Ben-Hur
185 Warrior
186 Hacksaw Ridge
187 Fargo
188 Mad Max: Fury Road
189 Million Dollar Baby
190 Ratatouille
191 Children of Heaven
192 My Neighbor Totoro
193 Gran Torino
194 Raging Bull
195 12 Years a Slave
196 How to Train Your Dragon
197 Memories of Murder
198 The Grand Budapest Hotel
199 Before Sunrise
200 Blade Runner
201 Monsters, Inc.
202 Gone Girl
203 Ford v Ferrari
204 Jaws
205 In the Name of the Father
206 Spider-Man: No Way Home
207 Wild Tales
208 The Gold Rush
209 Chainsaw Man - The Movie: Reze Arc
210 Sherlock Jr.
211 Mary and Max
212 A Silent Voice: The Movie
213 The Wages of Fear
214 The Deer Hunter
215 Logan
216 Rocky
217 Pirates of the Caribbean: The Curse of the Black Pearl
218 The General
219 Mr. Smith Goes to Washington
220 Tokyo Story
221 La haine
222 Spotlight
223 The Sound of Music
224 Maharaja
225 Jai Bhim
226 The Terminator
227 Wild Strawberries
228 On the Waterfront
229 The Best Years of Our Lives
230 The Third Man
231 The Chaos Class Failed the Class
232 The Big Lebowski
233 The Incredibles
234 Before Sunset
235 Hachi: A Dog's Tale
236 Room
237 Hotel Rwanda
238 The Exorcist
239 The Seventh Seal
240 Platoon
241 The Iron Giant
242 Rush
243 Stand by Me
244 The Wizard of Oz
245 The Battle of Algiers
246 My Father and My Son
247 The Passion of Joan of Arc
248 The Handmaiden
249 Hera Pheri

In [32]:
Certificate_fixed = []

for movie in Movie_Name:
    certificate = movie.find_elements(
        "xpath",
        "./ancestor::li[1]//div[contains(@class,'cli-title-metadata')]//li[3]"
    )

    if len(certificate) > 0:
        Certificate_fixed.append(certificate[0].text)
    else:
        Certificate_fixed.append(None)

In [33]:
print(len(Certificate_fixed))
print(Certificate_fixed[:10])
print(Certificate_fixed.count(None))

250
['R', 'R', 'PG-13', 'R', 'PG-13', 'Approved', 'R', 'PG-13', 'R', 'PG-13']
6

In [34]:
print(len(Movie_Name))

250

In [35]:
print(len(Certificate_fixed))

250

In [36]:
print("Movie Names:", len(Movie_Name))
print("Release Years:", len(Release_Year))
print("Runtime:", len(Runtime))
print("Certificate_fixed:", len(Certificate_fixed))
print("Ratings:", len(Rate))

Movie Names: 250
Release Years: 250
Runtime: 250
Certificate_fixed: 250
Ratings: 250

In [37]:
import pandas as pd

In [38]:
movies = []

for i in range(len(Movie_Name)):
    movies.append({
        "Movie_Name": Movie_Name[i].text,
        "Release_Year": Release_Year[i].text,
        "Runtime": Runtime[i].text,
        "Certificate": Certificate_fixed[i],
        "Rate": Rate[i].text
    })

df = pd.DataFrame(movies)

In [39]:
print(len(movies))

250

In [40]:
print(movies[-1])

{'Movie_Name': 'Hera Pheri', 'Release_Year': '2000', 'Runtime': '2h 36m', 'Certificate': 'Not Rated', 'Rate': '8.2'}

In [41]:
import pandas as pd

df = pd.DataFrame(movies)

In [42]:
df.head()

,Movie_Name,Release_Year,Runtime,Certificate,Rate
0,The Shawshank Redemption,1994,2h 22m,R,9.3
1,The Godfather,1972,2h 55m,R,9.2
2,The Dark Knight,2008,2h 32m,PG-13,9.1
3,The Godfather Part II,1974,3h 22m,R,9.0
4,The Lord of the Rings: The Return of the King,2003,3h 21m,PG-13,9.0

In [43]:
print(df.shape)

(250, 5)

In [44]:
print(df.isnull().sum())

Movie_Name      0
Release_Year    0
Runtime         0
Certificate     6
Rate            0
dtype: int64

In [45]:
print(df.duplicated().sum())

0

In [46]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Movie_Name    250 non-null    str
 1   Release_Year  250 non-null    str
 2   Runtime       250 non-null    str
 3   Certificate   244 non-null    str
 4   Rate          250 non-null    str
dtypes: str(5)
memory usage: 9.9 KB

In [47]:
df

,Movie_Name,Release_Year,Runtime,Certificate,Rate
0,The Shawshank Redemption,1994,2h 22m,R,9.3
1,The Godfather,1972,2h 55m,R,9.2
2,The Dark Knight,2008,2h 32m,PG-13,9.1
3,The Godfather Part II,1974,3h 22m,R,9.0
4,The Lord of the Rings: The Return of the King,2003,3h 21m,PG-13,9.0
...,...,...,...,...,...
245,The Battle of Algiers,1966,2h 1m,Not Rated,8.1
246,My Father and My Son,2005,1h 52m,Not Rated,8.2
247,The Passion of Joan of Arc,1928,1h 54m,Passed,8.1
248,The Handmaiden,2016,2h 25m,Not Rated,8.1
249,Hera Pheri,2000,2h 36m,Not Rated,8.2

In [48]:
df.tail()

                     Movie_Name Release_Year Runtime Certificate Rate
245       The Battle of Algiers         1966   2h 1m   Not Rated  8.1
246        My Father and My Son         2005  1h 52m   Not Rated  8.2
247  The Passion of Joan of Arc         1928  1h 54m      Passed  8.1
248              The Handmaiden         2016  2h 25m   Not Rated  8.1
249                  Hera Pheri         2000  2h 36m   Not Rated  8.2

In [49]:
df.iloc[148]

Movie_Name      Casino
Release_Year      1995
Runtime         2h 58m
Certificate          R
Rate               8.2
Name: 148, dtype: str

In [50]:
df.iloc[185]

Movie_Name      Warrior
Release_Year       2011
Runtime          2h 20m
Certificate       PG-13
Rate                8.1
Name: 185, dtype: str

In [51]:
# Mark Maged

In [52]:
df['Movie_Name'] = df['Movie_Name'].str.strip()
df['Certificate'] = df['Certificate'].str.strip()

In [53]:
df['Release_Year'] = df['Release_Year'].astype(int)

In [54]:
df['Certificate'] = df['Certificate'].fillna('Not Rated')

In [55]:
df

,Movie_Name,Release_Year,Runtime,Certificate,Rate
0,The Shawshank Redemption,1994,2h 22m,R,9.3
1,The Godfather,1972,2h 55m,R,9.2
2,The Dark Knight,2008,2h 32m,PG-13,9.1
3,The Godfather Part II,1974,3h 22m,R,9.0
4,The Lord of the Rings: The Return of the King,2003,3h 21m,PG-13,9.0
...,...,...,...,...,...
245,The Battle of Algiers,1966,2h 1m,Not Rated,8.1
246,My Father and My Son,2005,1h 52m,Not Rated,8.2
247,The Passion of Joan of Arc,1928,1h 54m,Passed,8.1
248,The Handmaiden,2016,2h 25m,Not Rated,8.1
249,Hera Pheri,2000,2h 36m,Not Rated,8.2

In [56]:
df['Rate'] = df['Rate'].astype(float)

In [57]:
df.drop_duplicates(inplace=True)
df.reset_index(drop=True,inplace=True)

In [58]:
print(df.dtypes)
print()
print(df.isnull().sum())
df

Movie_Name          str
Release_Year      int64
Runtime             str
Certificate         str
Rate            float64
dtype: object

Movie_Name      0
Release_Year    0
Runtime         0
Certificate     0
Rate            0
dtype: int64

,Movie_Name,Release_Year,Runtime,Certificate,Rate
0,The Shawshank Redemption,1994,2h 22m,R,9.3
1,The Godfather,1972,2h 55m,R,9.2
2,The Dark Knight,2008,2h 32m,PG-13,9.1
3,The Godfather Part II,1974,3h 22m,R,9.0
4,The Lord of the Rings: The Return of the King,2003,3h 21m,PG-13,9.0
...,...,...,...,...,...
245,The Battle of Algiers,1966,2h 1m,Not Rated,8.1
246,My Father and My Son,2005,1h 52m,Not Rated,8.2
247,The Passion of Joan of Arc,1928,1h 54m,Passed,8.1
248,The Handmaiden,2016,2h 25m,Not Rated,8.1
249,Hera Pheri,2000,2h 36m,Not Rated,8.2

In [59]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Movie_Name    250 non-null    str
 1   Release_Year  250 non-null    int64
 2   Runtime       250 non-null    str
 3   Certificate   250 non-null    str
 4   Rate          250 non-null    float64
dtypes: float64(1), int64(1), str(3)
memory usage: 9.9 KB

In [60]:
df['Rate']

0      9.3
1      9.2
2      9.1
3      9.0
4      9.0
      ...
245    8.1
246    8.2
247    8.1
248    8.1
249    8.2
Name: Rate, Length: 250, dtype: float64

In [61]:
df['Certificate']

0              R
1              R
2          PG-13
3              R
4          PG-13
         ...
245    Not Rated
246    Not Rated
247       Passed
248    Not Rated
249    Not Rated
Name: Certificate, Length: 250, dtype: str

In [62]:
df.loc[df['Rate'] == 8.1]

,Movie_Name,Release_Year,Runtime,Certificate,Rate
166,Monty Python and the Holy Grail,1975,1h 31m,PG,8.1
167,Dial M for Murder,1954,1h 45m,PG,8.1
170,"Lock, Stock and Two Smoking Barrels",1998,1h 47m,R,8.1
171,Chinatown,1974,2h 10m,R,8.1
172,Catch Me If You Can,2002,2h 21m,PG-13,8.1
...,...,...,...,...,...
243,Stand by Me,1986,1h 29m,R,8.1
244,The Wizard of Oz,1939,1h 42m,G,8.1
245,The Battle of Algiers,1966,2h 1m,Not Rated,8.1
247,The Passion of Joan of Arc,1928,1h 54m,Passed,8.1
248,The Handmaiden,2016,2h 25m,Not Rated,8.1

In [63]:
df.loc[df['Certificate'] == 'R']

                   Movie_Name  Release_Year Runtime Certificate  Rate
0    The Shawshank Redemption          1994  2h 22m           R   9.3
1               The Godfather          1972  2h 55m           R   9.2
3       The Godfather Part II          1974  3h 22m           R   9.0
6            Schindler's List          1993  3h 16m           R   9.0
8                Pulp Fiction          1994  2h 34m           R   8.8
..                        ...           ...     ...         ...   ...
236                      Room          2015  1h 58m           R   8.1
238              The Exorcist          1973   2h 2m           R   8.1
240                   Platoon          1986      2h           R   8.0
242                      Rush          2013   2h 3m           R   8.1
243               Stand by Me          1986  1h 29m           R   8.1

[103 rows x 5 columns]

In [64]:
df.tail()

                     Movie_Name  Release_Year Runtime Certificate  Rate
245       The Battle of Algiers          1966   2h 1m   Not Rated   8.1
246        My Father and My Son          2005  1h 52m   Not Rated   8.2
247  The Passion of Joan of Arc          1928  1h 54m      Passed   8.1
248              The Handmaiden          2016  2h 25m   Not Rated   8.1
249                  Hera Pheri          2000  2h 36m   Not Rated   8.2

In [65]:
df.iloc[165]

Movie_Name      The Great Escape
Release_Year                1963
Runtime                   2h 52m
Certificate             Approved
Rate                         8.2
Name: 165, dtype: object